name: Issues sample
on: 
  issues:
    types: [opened, edited, closed]
jobs:
  details:
    runs-on: ubuntu-latest
    steps:
      - name: show-info
        run: echo "${{ toJSON(github.event.issue) }}"